version: 0.0.{build}
platform:
  - x64
cache:
  - c:\tools\vcpkg\installed\
environment:
  CODECOV_TOKEN:
    secure: dz7q7ZdmeAjy2gMUTZFiCt7z9tuGAEWwLF0IP08oqD6JSjYsv1y3vEqDWF6/Vgns
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    ARCH: x64
    QT_COMPILER: msvc2017_64
    QT_VERSION: 5.10.1
install:
  - git submodule update --init --recursive
  - cmd: set VCPKG_DEFAULT_TRIPLET=x64-windows
  - cmd: vcpkg install gtest
  - sh: sudo apt update; sudo apt install -y qt5-default lcov
  - sh: mkdir ~/googletest
  - sh: pushd ~/googletest
  - sh: wget -qO - https://github.com/google/googletest/archive/release-1.8.0.tar.gz | tar -xz
  - sh: cmake -D CMAKE_INSTALL_PREFIX:PATH=$HOME/googletest -D CMAKE_BUILD_TYPE=Release googletest-release-1.8.0
  - sh: make install
  - sh: popd
build_script:
  - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat" %ARCH%
  - mkdir build
  - cd build
  - cmd: cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DQt5_DIR=C:/Qt/%QT_VERSION%/%QT_COMPILER%/lib/cmake/Qt5 -DCMAKE_BUILD_TYPE=Release ..
  - sh: cmake -DCMAKE_BUILD_TYPE=Debug -DGTEST_ROOT:PATH=$HOME/googletest ..
  - cmake --build .
test_script:
  - sh: ../.bin/Debug/lib_tests --gtest_output="xml:tests.xml"
after_test:
  - sh: lcov -c -d . -o coverage.info
  - sh: lcov -r coverage.info '*/mingw64/*' '*/mingw32/*' '/c/Qt/*' '*/test/*' -o coverage.info
  - sh: bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  - sh: curl --data-binary @tests.xml https://ci.appveyor.com/api/testresults/junit/$APPVEYOR_JOB_ID