set(QT_COMPONENTS Gui Widgets)
find_package(Qt5 REQUIRED COMPONENTS ${QT_COMPONENTS})
set(Qt5_COMPONENT_LIBRARIES ${Qt5Core_LIBRARIES} ${Qt5Gui_LIBRARIES} ${Qt5Widgets_LIBRARIES})
list(GET Qt5Widgets_INCLUDE_DIRS 0 Qt5_ROOT)
get_filename_component(Qt5_ROOT ${Qt5_ROOT} DIRECTORY)
message(STATUS "Qt5_ROOT: ${Qt5_ROOT}")

function(enable_qt5 TARGET)
	#set_target_properties(${TARGET} PROPERTIES AUTOMOC ON)
	#set_target_properties(${TARGET} PROPERTIES AUTORCC ON)
	#set_target_properties(${TARGET} PROPERTIES AUTOUIC ON)
	set_target_properties(${TARGET} PROPERTIES CMAKE_INCLUDE_CURRENT_DIR ON)
	target_link_libraries(${TARGET} ${Qt5_COMPONENT_LIBRARIES})
	get_target_property(TARGET_TYPE ${TARGET} TYPE)
	if (WIN32 AND TARGET_TYPE STREQUAL "EXECUTABLE")
		message(STATUS "Enabling WindeployQT for ${TARGET}")
		if (CMAKE_BUILD_TYPE MATCHES Release OR CMAKE_BUILD_TYPE MATCHES MinSizeRel)
			set(Qt_WinDeployVersion "--release")
		endif ()
		add_custom_command(TARGET ${TARGET} POST_BUILD COMMAND "${Qt5_ROOT}/bin/windeployqt.exe" ARGS
			"$<TARGET_FILE:${TARGET}>" ${Qt_WinDeployVersion})
	endif ()
endfunction()